### PR TITLE
localization support, German (de) translation

### PR DESCRIPTION
**Pull request by jonnius**

### CODE REVIEW

**Comment by bertoldia** [comment]
Hey Jonnius,

I'm assuming you can speak English :) Thanks for the patch! I've made one
small change to it:
https://github.com/bertoldia/files-menu/commit/6266095d31483d2674963bc7d1ce16d9853941dc
in a branch named _jonnius-master_.

Could you please test that it doesn't break your changes? If it works I'll
merge it asap.

Danke!
axel.

**Comment by jonnius** [comment]
It didn't work with your changes. I guess by the moment the vars are beeing initialized, gettext is not. So you need the _(·) on every use of the vars. The initialization of the vars should still be in those brakets, too, so that the pot file could be created...
I used you commit and fixed it.

**Comment by bertoldia** [comment]
Aw nuts. Thanks a lot gettext. Will look at this again soon.

**Comment by bertoldia** [comment]
How about this? I've kept the constants but do the gettext lookups at the
call sites.

axel.

**Comment by jonnius** [comment]
Where to find your changes? You can try yourself restarting GNOME Shell in German with the command
LANG=de_DE.utf8 gnome-shell --replace

**Comment by bertoldia** [comment]
Hi Jonnius, is this fixed in the current master?

**Pull request closed without merging**
